name: cc-reporter

on:
  push:
    branches:
      - main
env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DATABASE_URL: 'sqlite:///db.sqlite3'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry
          make install
          pip install coverage
      - name: Test & calculate coverage
        run: |
          poetry run python3 -m coverage run manage.py test
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_CODE }}
        with:
          coverageCommand: python3 -m coverage xml
          debug: true
